[package]
name = "reallive"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
encoding_rs = "0.8"
ab_glyph = "0.2"
siglus_assets = { path = "../siglus_assets" }
avg32 = { path = "../avg32" }
image.workspace = true

[features]
desktop-player = ["dep:bytemuck", "dep:clap", "dep:pollster", "dep:wgpu", "dep:winit"]

[target.'cfg(not(target_os = "horizon"))'.dependencies]
kira.workspace = true
bytemuck = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
pollster = { workspace = true, optional = true }
wgpu = { workspace = true, optional = true }
winit = { workspace = true, optional = true }

[[bin]]
name = "reallive_player"
path = "src/bin/reallive_player.rs"
required-features = ["desktop-player"]

[lints]
workspace = true
