[package]
name = "avg32"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
encoding_rs = "0.8"
engine-detect = { path = "../engine-detect" }
ab_glyph = "0.2"

[features]
desktop-player = ["dep:bytemuck", "dep:clap", "dep:pollster", "dep:wgpu", "dep:winit"]

[target.'cfg(not(target_os = "horizon"))'.dependencies]
kira.workspace = true
oxideav-cinepak = { version = "0.0.3", default-features = false }
bytemuck = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
pollster = { workspace = true, optional = true }
wgpu = { workspace = true, optional = true }
winit = { workspace = true, optional = true }

[[bin]]
name = "avg32_player"
path = "src/bin/avg32_player.rs"
required-features = ["desktop-player"]

[lints]
workspace = true
