[package]
name = "siglus_vita_player"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
build = "build.rs"

[workspace]

[package.metadata.vita]
title_id = "SIGVITA02"
title_name = "Siglus Vita"
build_std = "std,panic_abort"

[target.'cfg(target_os = "vita")'.dependencies]
siglus_scene_vm = { path = "../../../crates/siglus_scene_vm" }
vitasdk-sys = { version = "=0.3.3", default-features = false, features = ["SceAudio_stub", "SceCtrl_stub", "SceSysmem_stub", "SceTouch_stub"] }
