[package]
name = "siglus_omv_decoder"
version = "0.1.0"
edition.workspace = true

[lib]
name = "siglus_omv_decoder"
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1", default-features = false }
theora-rs = { path = "../theora-rs" }

[target.'cfg(target_os = "horizon")'.dependencies]
ogg_switch = { package = "ogg", path = "../../platform/switch/patches/ogg-0.9.2" }
lewton_switch = { package = "lewton", path = "../../platform/switch/patches/lewton-0.10.2" }

[target.'cfg(not(target_os = "horizon"))'.dependencies]
ogg = "0.9.2"
lewton = "0.10.2"

[lints]
workspace = true
