//! UK2 two-character opcode table recovered from `word_1A60A` and `jpt_19849`.
use std::fmt;
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum SingleOpcode {
    End,
    Assign,
    BlockCall,
    Decrement,
    Increment,
    Return,
}
impl SingleOpcode {
    pub fn from_byte(byte: u8) -> Option<Self> {
        Some(match byte {
            0x00 => Self::End,
            0x01 => Self::Assign,
            0x02 => Self::BlockCall,
            0x03 => Self::Decrement,
            0x04 => Self::Increment,
            b'R' => Self::Return,
            _ => return None,
        })
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum TwoOpcode {
    A0,
    D0,
    F0,
    I0,
    J0,
    L0,
    M0,
    T0,
    U0,
    A1,
    D1,
    F1,
    I1,
    J1,
    L1,
    M1,
    T1,
    U1,
    W1,
    A2,
    I2,
    J2,
    L2,
    M2,
    U2,
    W2,
    A3,
    I3,
    J3,
    L3,
    M3,
    U3,
    W3,
    A4,
    F4,
    I4,
    L4,
    M4,
    W4,
    A5,
    F5,
    I5,
    L5,
    M5,
    U5,
    W5,
    A6,
    F6,
    U6,
    W6,
    F7,
    U7,
    W7,
    F8,
    U8,
    W8,
    F9,
    U9,
    W9,
    FA,
    WA,
    FB,
    UB,
    WB,
    FC,
    WC,
    FD,
    UD,
    WD,
    FE,
    UE,
    WE,
    WF,
    FG,
    WG,
    FH,
    UH,
    WH,
    FI,
    UI,
    WI,
    FJ,
    UJ,
    WJ,
    FK,
    UK,
    WK,
    WL,
}
impl TwoOpcode {
    pub const ALL: [Self; 88] = [
        Self::A0,
        Self::D0,
        Self::F0,
        Self::I0,
        Self::J0,
        Self::L0,
        Self::M0,
        Self::T0,
        Self::U0,
        Self::A1,
        Self::D1,
        Self::F1,
        Self::I1,
        Self::J1,
        Self::L1,
        Self::M1,
        Self::T1,
        Self::U1,
        Self::W1,
        Self::A2,
        Self::I2,
        Self::J2,
        Self::L2,
        Self::M2,
        Self::U2,
        Self::W2,
        Self::A3,
        Self::I3,
        Self::J3,
        Self::L3,
        Self::M3,
        Self::U3,
        Self::W3,
        Self::A4,
        Self::F4,
        Self::I4,
        Self::L4,
        Self::M4,
        Self::W4,
        Self::A5,
        Self::F5,
        Self::I5,
        Self::L5,
        Self::M5,
        Self::U5,
        Self::W5,
        Self::A6,
        Self::F6,
        Self::U6,
        Self::W6,
        Self::F7,
        Self::U7,
        Self::W7,
        Self::F8,
        Self::U8,
        Self::W8,
        Self::F9,
        Self::U9,
        Self::W9,
        Self::FA,
        Self::WA,
        Self::FB,
        Self::UB,
        Self::WB,
        Self::FC,
        Self::WC,
        Self::FD,
        Self::UD,
        Self::WD,
        Self::FE,
        Self::UE,
        Self::WE,
        Self::WF,
        Self::FG,
        Self::WG,
        Self::FH,
        Self::UH,
        Self::WH,
        Self::FI,
        Self::UI,
        Self::WI,
        Self::FJ,
        Self::UJ,
        Self::WJ,
        Self::FK,
        Self::UK,
        Self::WK,
        Self::WL,
    ];

    pub fn from_pair(first: u8, second: u8) -> Option<Self> {
        Some(match [first, second] {
            [b'A', b'0'] => Self::A0,
            [b'D', b'0'] => Self::D0,
            [b'F', b'0'] => Self::F0,
            [b'I', b'0'] => Self::I0,
            [b'J', b'0'] => Self::J0,
            [b'L', b'0'] => Self::L0,
            [b'M', b'0'] => Self::M0,
            [b'T', b'0'] => Self::T0,
            [b'U', b'0'] => Self::U0,
            [b'A', b'1'] => Self::A1,
            [b'D', b'1'] => Self::D1,
            [b'F', b'1'] => Self::F1,
            [b'I', b'1'] => Self::I1,
            [b'J', b'1'] => Self::J1,
            [b'L', b'1'] => Self::L1,
            [b'M', b'1'] => Self::M1,
            [b'T', b'1'] => Self::T1,
            [b'U', b'1'] => Self::U1,
            [b'W', b'1'] => Self::W1,
            [b'A', b'2'] => Self::A2,
            [b'I', b'2'] => Self::I2,
            [b'J', b'2'] => Self::J2,
            [b'L', b'2'] => Self::L2,
            [b'M', b'2'] => Self::M2,
            [b'U', b'2'] => Self::U2,
            [b'W', b'2'] => Self::W2,
            [b'A', b'3'] => Self::A3,
            [b'I', b'3'] => Self::I3,
            [b'J', b'3'] => Self::J3,
            [b'L', b'3'] => Self::L3,
            [b'M', b'3'] => Self::M3,
            [b'U', b'3'] => Self::U3,
            [b'W', b'3'] => Self::W3,
            [b'A', b'4'] => Self::A4,
            [b'F', b'4'] => Self::F4,
            [b'I', b'4'] => Self::I4,
            [b'L', b'4'] => Self::L4,
            [b'M', b'4'] => Self::M4,
            [b'W', b'4'] => Self::W4,
            [b'A', b'5'] => Self::A5,
            [b'F', b'5'] => Self::F5,
            [b'I', b'5'] => Self::I5,
            [b'L', b'5'] => Self::L5,
            [b'M', b'5'] => Self::M5,
            [b'U', b'5'] => Self::U5,
            [b'W', b'5'] => Self::W5,
            [b'A', b'6'] => Self::A6,
            [b'F', b'6'] => Self::F6,
            [b'U', b'6'] => Self::U6,
            [b'W', b'6'] => Self::W6,
            [b'F', b'7'] => Self::F7,
            [b'U', b'7'] => Self::U7,
            [b'W', b'7'] => Self::W7,
            [b'F', b'8'] => Self::F8,
            [b'U', b'8'] => Self::U8,
            [b'W', b'8'] => Self::W8,
            [b'F', b'9'] => Self::F9,
            [b'U', b'9'] => Self::U9,
            [b'W', b'9'] => Self::W9,
            [b'F', b'A'] => Self::FA,
            [b'W', b'A'] => Self::WA,
            [b'F', b'B'] => Self::FB,
            [b'U', b'B'] => Self::UB,
            [b'W', b'B'] => Self::WB,
            [b'F', b'C'] => Self::FC,
            [b'W', b'C'] => Self::WC,
            [b'F', b'D'] => Self::FD,
            [b'U', b'D'] => Self::UD,
            [b'W', b'D'] => Self::WD,
            [b'F', b'E'] => Self::FE,
            [b'U', b'E'] => Self::UE,
            [b'W', b'E'] => Self::WE,
            [b'W', b'F'] => Self::WF,
            [b'F', b'G'] => Self::FG,
            [b'W', b'G'] => Self::WG,
            [b'F', b'H'] => Self::FH,
            [b'U', b'H'] => Self::UH,
            [b'W', b'H'] => Self::WH,
            [b'F', b'I'] => Self::FI,
            [b'U', b'I'] => Self::UI,
            [b'W', b'I'] => Self::WI,
            [b'F', b'J'] => Self::FJ,
            [b'U', b'J'] => Self::UJ,
            [b'W', b'J'] => Self::WJ,
            [b'F', b'K'] => Self::FK,
            [b'U', b'K'] => Self::UK,
            [b'W', b'K'] => Self::WK,
            [b'W', b'L'] => Self::WL,
            _ => return None,
        })
    }

    pub const fn bytes(self) -> [u8; 2] {
        match self {
            Self::A0 => *b"A0",
            Self::D0 => *b"D0",
            Self::F0 => *b"F0",
            Self::I0 => *b"I0",
            Self::J0 => *b"J0",
            Self::L0 => *b"L0",
            Self::M0 => *b"M0",
            Self::T0 => *b"T0",
            Self::U0 => *b"U0",
            Self::A1 => *b"A1",
            Self::D1 => *b"D1",
            Self::F1 => *b"F1",
            Self::I1 => *b"I1",
            Self::J1 => *b"J1",
            Self::L1 => *b"L1",
            Self::M1 => *b"M1",
            Self::T1 => *b"T1",
            Self::U1 => *b"U1",
            Self::W1 => *b"W1",
            Self::A2 => *b"A2",
            Self::I2 => *b"I2",
            Self::J2 => *b"J2",
            Self::L2 => *b"L2",
            Self::M2 => *b"M2",
            Self::U2 => *b"U2",
            Self::W2 => *b"W2",
            Self::A3 => *b"A3",
            Self::I3 => *b"I3",
            Self::J3 => *b"J3",
            Self::L3 => *b"L3",
            Self::M3 => *b"M3",
            Self::U3 => *b"U3",
            Self::W3 => *b"W3",
            Self::A4 => *b"A4",
            Self::F4 => *b"F4",
            Self::I4 => *b"I4",
            Self::L4 => *b"L4",
            Self::M4 => *b"M4",
            Self::W4 => *b"W4",
            Self::A5 => *b"A5",
            Self::F5 => *b"F5",
            Self::I5 => *b"I5",
            Self::L5 => *b"L5",
            Self::M5 => *b"M5",
            Self::U5 => *b"U5",
            Self::W5 => *b"W5",
            Self::A6 => *b"A6",
            Self::F6 => *b"F6",
            Self::U6 => *b"U6",
            Self::W6 => *b"W6",
            Self::F7 => *b"F7",
            Self::U7 => *b"U7",
            Self::W7 => *b"W7",
            Self::F8 => *b"F8",
            Self::U8 => *b"U8",
            Self::W8 => *b"W8",
            Self::F9 => *b"F9",
            Self::U9 => *b"U9",
            Self::W9 => *b"W9",
            Self::FA => *b"FA",
            Self::WA => *b"WA",
            Self::FB => *b"FB",
            Self::UB => *b"UB",
            Self::WB => *b"WB",
            Self::FC => *b"FC",
            Self::WC => *b"WC",
            Self::FD => *b"FD",
            Self::UD => *b"UD",
            Self::WD => *b"WD",
            Self::FE => *b"FE",
            Self::UE => *b"UE",
            Self::WE => *b"WE",
            Self::WF => *b"WF",
            Self::FG => *b"FG",
            Self::WG => *b"WG",
            Self::FH => *b"FH",
            Self::UH => *b"UH",
            Self::WH => *b"WH",
            Self::FI => *b"FI",
            Self::UI => *b"UI",
            Self::WI => *b"WI",
            Self::FJ => *b"FJ",
            Self::UJ => *b"UJ",
            Self::WJ => *b"WJ",
            Self::FK => *b"FK",
            Self::UK => *b"UK",
            Self::WK => *b"WK",
            Self::WL => *b"WL",
        }
    }

    /// IDA offset of the handler in the Sorcer Kingdom reference `UK2.EXE`.
    pub const fn reference_handler(self) -> u32 {
        match self {
            Self::A0 => 0x1A4BB,
            Self::D0 => 0x19C4E,
            Self::F0 => 0x1A0DF,
            Self::I0 => 0x1A561,
            Self::J0 => 0x1984E,
            Self::L0 => 0x198ED,
            Self::M0 => 0x1A470,
            Self::T0 => 0x1A049,
            Self::U0 => 0x19D04,
            Self::A1 => 0x1A4D3,
            Self::D1 => 0x19C53,
            Self::F1 => 0x1A0F7,
            Self::I1 => 0x1A594,
            Self::J1 => 0x19866,
            Self::L1 => 0x198F4,
            Self::M1 => 0x1A484,
            Self::T1 => 0x1A0A3,
            Self::U1 => 0x19D14,
            Self::W1 => 0x19927,
            Self::A2 => 0x1A4DB,
            Self::I2 => 0x1A59B,
            Self::J2 => 0x198A8,
            Self::L2 => 0x198FB,
            Self::M2 => 0x1A49D,
            Self::U2 => 0x19D30,
            Self::W2 => 0x19955,
            Self::A3 => 0x1A506,
            Self::I3 => 0x1A5A5,
            Self::J3 => 0x198DD,
            Self::L3 => 0x19902,
            Self::M3 => 0x1A5F0,
            Self::U3 => 0x19D40,
            Self::W3 => 0x19962,
            Self::A4 => 0x1A523,
            Self::F4 => 0x1A119,
            Self::I4 => 0x1A5C9,
            Self::L4 => 0x19909,
            Self::M4 => 0x1A4A5,
            Self::W4 => 0x1997F,
            Self::A5 => 0x1A544,
            Self::F5 => 0x1A182,
            Self::I5 => 0x1A5D0,
            Self::L5 => 0x1991D,
            Self::M5 => 0x1A4AD,
            Self::U5 => 0x19DA2,
            Self::W5 => 0x199BE,
            Self::A6 => 0x1A559,
            Self::F6 => 0x1A1A4,
            Self::U6 => 0x19DDB,
            Self::W6 => 0x199E1,
            Self::F7 => 0x1A1B9,
            Self::U7 => 0x19E25,
            Self::W7 => 0x19A17,
            Self::F8 => 0x1A1CE,
            Self::U8 => 0x19E5F,
            Self::W8 => 0x19A29,
            Self::F9 => 0x1A1F6,
            Self::U9 => 0x19E8D,
            Self::W9 => 0x19A31,
            Self::FA => 0x1A244,
            Self::WA => 0x19A7A,
            Self::FB => 0x1A25F,
            Self::UB => 0x19EA4,
            Self::WB => 0x19A94,
            Self::FC => 0x1A2A2,
            Self::WC => 0x19A55,
            Self::FD => 0x1A2A2,
            Self::UD => 0x19F1B,
            Self::WD => 0x19ACF,
            Self::FE => 0x1A330,
            Self::UE => 0x19F4E,
            Self::WE => 0x19B12,
            Self::WF => 0x19B22,
            Self::FG => 0x1A384,
            Self::WG => 0x19B3F,
            Self::FH => 0x1A3A5,
            Self::UH => 0x19FAA,
            Self::WH => 0x19B66,
            Self::FI => 0x1A40F,
            Self::UI => 0x19FD3,
            Self::WI => 0x19BB7,
            Self::FJ => 0x1A424,
            Self::UJ => 0x19FFB,
            Self::WJ => 0x19BCF,
            Self::FK => 0x1A458,
            Self::UK => 0x1A034,
            Self::WK => 0x19BFF,
            Self::WL => 0x19C22,
        }
    }

    /// Compact encoding signature used by the decoder documentation.
    /// `D` = direct operand, `E` = expression, `X` = null-terminated expression
    /// list, `C` = condition, and `O16` = raw little-endian file offset.
    pub const fn signature(self) -> &'static str {
        match self {
            Self::A0 => "D",
            Self::D0 => "E X<=30",
            Self::F0 => "D",
            Self::I0 => "D X<=8",
            Self::J0 => "O16",
            Self::L0 => "C O16",
            Self::M0 => "D",
            Self::T0 => "X*",
            Self::U0 => "E",
            Self::A1 => "",
            Self::D1 => "E E",
            Self::F1 => "E D",
            Self::I1 => "",
            Self::J1 => "O16",
            Self::L1 => "C O16",
            Self::M1 => "X<=1",
            Self::T1 => "X*",
            Self::U1 => "X<=2",
            Self::W1 => "X<=7",
            Self::A2 => "D D D D D D",
            Self::I2 => "",
            Self::J2 => "D",
            Self::L2 => "O16",
            Self::M2 => "",
            Self::U2 => "E X<=30",
            Self::W2 => "",
            Self::A3 => "X<=20",
            Self::I3 => "D X<=1",
            Self::J3 => "D",
            Self::L3 => "D E E E O16",
            Self::M3 => "",
            Self::U3 => "X<=2 D",
            Self::W3 => "E",
            Self::A4 => "X<=20",
            Self::F4 => "D D D E D D",
            Self::I4 => "",
            Self::L4 => "C O16",
            Self::M4 => "",
            Self::W4 => "X<=2",
            Self::A5 => "D",
            Self::F5 => "E",
            Self::I5 => "D",
            Self::L5 => "C O16",
            Self::M5 => "X<=2",
            Self::U5 => "D E",
            Self::W5 => "D E",
            Self::A6 => "",
            Self::F6 => "D",
            Self::U6 => "E E",
            Self::W6 => "E D E",
            Self::F7 => "D",
            Self::U7 => "E",
            Self::W7 => "E",
            Self::F8 => "E",
            Self::U8 => "X<=2",
            Self::W8 => "D E E E X<=20",
            Self::F9 => "X<=3",
            Self::U9 => "D",
            Self::W9 => "E",
            Self::FA => "X<=5",
            Self::WA => "E",
            Self::FB => "X<=5",
            Self::UB => "D D",
            Self::WB => "X<=2",
            Self::FC => "X<=2",
            Self::WC => "E",
            Self::FD => "X<=2",
            Self::UD => "E D",
            Self::WD => "E",
            Self::FE => "D",
            Self::UE => "E RESOURCE_LIST",
            Self::WE => "E",
            Self::WF => "E",
            Self::FG => "D",
            Self::WG => "",
            Self::FH => "X<=2 D D D D D",
            Self::UH => "E",
            Self::WH => "X<=5",
            Self::FI => "D",
            Self::UI => "X<=6",
            Self::WI => "E",
            Self::FJ => "X<=3",
            Self::UJ => "E D",
            Self::WJ => "D E D",
            Self::FK => "",
            Self::UK => "E",
            Self::WK => "X<=6",
            Self::WL => "X<=4",
        }
    }
}
impl fmt::Display for TwoOpcode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let bytes = self.bytes();
        f.write_str(std::str::from_utf8(&bytes).expect("UK2 opcode is ASCII"))
    }
}
